name: "Publish"

on:
    workflow_dispatch:
        inputs:
            branches:
                description: 'List of branches to be published'
                required: true
                default: "['1.19.2', '1.19.3', '1.19.4', '1.20.1', '1.20.2', '1.20.4']"
                type: string

jobs:
    publish:
        runs-on: ubuntu-latest
        name: Publish ${{ matrix.branch }}
        timeout-minutes: 60
        strategy:
            max-parallel: 3
            fail-fast: false
            matrix:
                branch: ${{ fromJson(inputs.branches) }}

        steps:
            -   name: "Checkout repository"
                uses: actions/checkout@v4.1.1
                with:
                    ref: ${{ matrix.branch }}
                    fetch-depth: 0

            -   name: "Set up JDK"
                uses: actions/setup-java@v4.0.0
                with:
                    java-version: 17
                    distribution: temurin

            -   name: "Parse gradle properties"
                id: gradle-properties
                run: |
                    while IFS='=' read -r key value; do
                      key=$(echo $key | awk '{$1=$1;print}')
                        value=$(echo $value | awk '{$1=$1;print}')
                    
                        case "$key" in
                          minecraft_version) echo "MINECRAFT_VERSION=$value" >> $GITHUB_OUTPUT ;;
                          mod_name) echo "MOD_NAME=$value" >> $GITHUB_OUTPUT ;;
                          mod_version) echo "MOD_VERSION=$value" >> $GITHUB_OUTPUT ;;
                        esac
                    done < gradle.properties

            -   name: "Parse changelog"
                id: parse-changelog
                run: |
                    changelog=$(cat CHANGELOG.md)
                    tag=${{ steps.gradle-properties.outputs.MOD_VERSION }}

                    list=$(echo "$changelog" | sed -n "/^## $tag$/,/^## [0-9]/ {
                    /^## [0-9]/d;
                    p
                    }" | sed '1d;/^$/d')

                    echo "$list" > RELEASE_CHANGELOG.md

            -   name: "Create github release"
                continue-on-error: true
                uses: ncipollo/release-action@v1
                with:
                    skipIfReleaseExists: true
                    allowUpdates: true
                    omitNameDuringUpdate: true
                    omitBodyDuringUpdate: true
                    tag: mc${{ steps.gradle-properties.outputs.MINECRAFT_VERSION }}-${{ steps.gradle-properties.outputs.MOD_VERSION }}
                    name: ${{ steps.gradle-properties.outputs.MOD_NAME }} ${{ steps.gradle-properties.outputs.MOD_VERSION }} for Minecraft ${{ steps.gradle-properties.outputs.MINECRAFT_VERSION }}
                    bodyFile: RELEASE_CHANGELOG.md

            -   name: "Run gradle build"
                uses: gradle/gradle-build-action@v2.11.1
                with:
                    cache-read-only: true
                    generate-job-summary: false
                    gradle-version: wrapper
                    arguments: build

            -   name: "Run gradle mergeJars"
                uses: gradle/gradle-build-action@v2.11.1
                with:
                    cache-read-only: true
                    generate-job-summary: false
                    gradle-version: wrapper
                    arguments: mergeJars

            -   name: Publish
                uses: Kir-Antipov/mc-publish@v3.3.0
                with:
                    github-token: ${{ secrets.GITHUB_TOKEN }}
                    github-tag: mc${{ steps.gradle-properties.outputs.MINECRAFT_VERSION }}-${{ steps.gradle-properties.outputs.MOD_VERSION }}

                    curseforge-id: ${{ vars.CURSEFORGE_PROJECT_ID }}
                    curseforge-token: ${{ secrets.CURSEFORGE_RELEASE_TOKEN }}

                    modrinth-id: ${{ vars.MODRINTH_PROJECT_ID }}
                    modrinth-featured: true
                    modrinth-token: ${{ secrets.MODRINTH_RELEASE_TOKEN }}

                    name: ${{ steps.gradle-properties.outputs.MOD_NAME }} ${{ steps.gradle-properties.outputs.MOD_VERSION }}
                    version: mc${{ steps.gradle-properties.outputs.MINECRAFT_VERSION }}-${{ steps.gradle-properties.outputs.MOD_VERSION }}
                    loaders: |
                        fabric
                        forge
                        neoforge
                        quilt
                    game-versions: "${{ matrix.branch }}"
                    dependencies: ""
                    changelog-file: RELEASE_CHANGELOG.md
                    files: |
                        build/libs/merged/!(*-@(dev|dev-shadow|sources|javadoc)).jar

    clear-cache:
        needs: publish
        runs-on: ubuntu-latest
        name: "Clear cache"
        timeout-minutes: 60
        steps:
            -   uses: MyAlbum/purge-cache@v2
                with:
                    accessed: true
                    created: true
                    max-age: 21600